# Generated by Django 4.2.3 on 2023-07-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_teach',
        ),
    ]
