# Generated by Django 4.2.3 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_is_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user-avatar.png', null=True, upload_to='posts/'),
        ),
    ]
