# Generated by Django 4.2.3 on 2023-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.CharField(default='', max_length=3, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
