# Generated by Django 4.2.3 on 2023-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_club_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='index',
            field=models.IntegerField(default=0, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
