# Generated by Django 4.2.3 on 2023-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_news_image_news_image_url_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.CharField(max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Source'),
        ),
    ]
