# Generated by Django 4.2.3 on 2023-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_club_image_alter_news_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(default='', max_length=200, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Height'),
            preserve_default=False,
        ),
    ]
