# Generated by Django 4.2.3 on 2023-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_player_surname_player_image_player_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='index',
            field=models.IntegerField(verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Number'),
        ),
    ]
