# Generated by Django 4.2.3 on 2023-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_player_index_alter_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='index',
            field=models.IntegerField(null=True, verbose_name='Index'),
        ),
    ]
