# Generated by Django 4.2.3 on 2023-07-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('played', models.IntegerField(verbose_name='Played')),
                ('won', models.IntegerField(verbose_name='won')),
                ('lost', models.IntegerField(verbose_name='lost')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
            ],
            options={
                'verbose_name': 'Standings',
                'verbose_name_plural': 'Standingss',
            },
        ),
    ]
