# Generated by Django 4.2.3 on 2023-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_news_image_url_alter_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='static/images/img-01_002.jpg', max_length=300, null=True, verbose_name='Image'),
        ),
    ]
