# Generated by Django 4.2.3 on 2023-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_news_image_url_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
    ]
