# Generated by Django 4.2.3 on 2023-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='https://www.imgacademy.com/sites/default/files/styles/scale_2500w/public/2020-08/rsz_esx_9767.jpg?itok=A4WOOH5W', max_length=300, verbose_name='Image'),
        ),
    ]
