# Generated by Django 4.2.3 on 2023-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='https://www.imgacademy.com/sites/default/files/styles/scale_2500w/public/2020-08/rsz_esx_9767.jpg?itok=A4WOOH5W', max_length=400, verbose_name='Image'),
        ),
    ]
