# Generated by Django 4.2.3 on 2023-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_news_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of function')),
                ('time', models.DateTimeField(verbose_name='DateTime')),
            ],
            options={
                'verbose_name': 'LastUpdated',
                'verbose_name_plural': 'LastUpdateds',
            },
        ),
    ]
